import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id);
const groups={shell:['Terrain shell','#646768'],baffles:['Optical cells','#616b70'],pcb:['LED boards','#327c63'],mounts:['Shell fittings','#b0bcc0'],frame:['Printed cage','#b1bfbd'],support:['Spine & spokes','#bba881'],controllers:['Controller carriers','#8596a1'],'controller-boards':['Sector boards','#317e67'],'component-clearance':['Tile component envelopes','#5993b2'],'controller-envelopes':['Sector component envelopes','#647887'],base:['Weighted base','#b2a37f']};
let renderer,camera,controls,scene,root,prototype,records=[],batches=[],mode='cutaway',spread=.6,ready=false;
const enabled=Object.fromEntries(Object.keys(groups).map(k=>[k,true]));let queued=false;
function redraw(){if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;controls?.update();renderer?.render(scene,camera);});}}
function select(record){$('part-title').textContent=record.name;const envelope=record.group.includes('envelope')||record.group==='component-clearance'||record.name.includes('envelope');const description=envelope?'Reserved component envelope. Body outline comes from the footprint or module allowance; verify purchased-part dimensions.':record.group==='pcb'?'Manufactured board outline and mounting holes. Routing and electrical qualification status are documented in the report.':'Generated manufacturing boundary. Print-process fit and material performance require the specified physical tests.';$('part-description').textContent=description;const size=record.box.getSize(new THREE.Vector3());$('part-specs').replaceChildren(...[['Group',groups[record.group]?.[0]||'Prototype'],['Part bounds',size.toArray().map(v=>v.toFixed(1)).join(' × ')+' mm'],['Geometry',envelope?'Assumed body envelope':'CAD mesh'],['Release',record.name.startsWith('sample-A1-')?'Sample A1':'A0 engineering prototype']].map(([a,b])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b;div.append(dt,dd);return div;}));}
function reset(){const sample=mode==='prototype';controls.target.set(0,0,sample?0:-32);camera.position.set(...(sample?[65,-80,65]:[420,-510,275]));if(mode==='exploded')camera.position.sub(controls.target).multiplyScalar(1.2).add(controls.target);if(camera.aspect<.85)camera.position.sub(controls.target).multiplyScalar(.85/camera.aspect).add(controls.target);controls.minDistance=sample?35:220;controls.maxDistance=sample?450:1800;controls.update();redraw();}
function update(){
 if(!ready)return;root.visible=mode!=='prototype';prototype.visible=mode==='prototype';const fronts=new Set(['shell','baffles','pcb','mounts','component-clearance']);
 for(const r of records){let show=enabled[r.group];if(mode==='frame'&&fronts.has(r.group))show=false;if(mode==='cutaway'&&fronts.has(r.group)&&r.center.y<15)show=false;r.visible=show;const matrix=r.original.clone();
  if(mode==='exploded'){let amount=r.group==='shell'?85:fronts.has(r.group)?38:r.group==='base'?-25:0;const shift=r.group==='base'?new THREE.Vector3(0,0,amount*spread):r.center.clone().normalize().multiplyScalar(amount*spread);matrix.elements[12]+=shift.x;matrix.elements[13]+=shift.y;matrix.elements[14]+=shift.z;}
  if(!show)matrix.scale(new THREE.Vector3(0,0,0));r.node.setMatrixAt(r.instance,matrix);
 }
 for(const batch of batches){batch.instanceMatrix.needsUpdate=true;batch.computeBoundingSphere();}
 for(const node of prototype.children){node.position.copy(node.userData.original);node.position.z+=spread*(node.userData.layer==='shell'?26:node.userData.layer==='baffles'?12:0);}
 $('spread-label').hidden=!['prototype','exploded'].includes(mode);$('spread-value').textContent=Math.round(spread*100)+'%';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));redraw();
}
async function load(){
 renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x111719,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;$('scene').append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,5000);camera.up.set(0,0,1);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.addEventListener('change',redraw);
 scene.add(new THREE.HemisphereLight(0xf0f2e7,0x36484e,2.1));for(const [color,intensity,position] of [[0xffe5c1,3.4,[200,-350,500]],[0xaccfe3,1.7,[-350,150,150]]]){const l=new THREE.DirectionalLight(color,intensity);l.position.set(...position);scene.add(l);}
 const loader=new GLTFLoader();const [gltf,index,sample]=await Promise.all([loader.loadAsync('assembly/assembly.glb',e=>{if(e.total)$('loading').textContent=`Loading CAD meshes… ${Math.round(e.loaded/e.total*100)}%`;}),fetch('assembly/assembly-index.json').then(r=>{if(!r.ok)throw Error('Missing assembly index');return r.json();}),loader.loadAsync('assembly/prototype.glb')]);const mats=new Set();for(const graph of [gltf.scene,sample.scene])graph.traverse(n=>{if(n.isMesh)mats.add(n.material);});for(const material of mats)material.color.convertSRGBToLinear();root=new THREE.Group();prototype=new THREE.Group();scene.add(root,prototype);const byName=new Map(index.map(r=>[r.name,r]));gltf.scene.updateMatrixWorld(true);const batchMap=new Map();
 gltf.scene.traverse(node=>{if(!node.isMesh)return;const meta=byName.get(node.name)||byName.get(node.parent?.name);if(!meta)return;node.geometry.computeBoundingBox();const box=node.geometry.boundingBox.clone(),center=box.getCenter(new THREE.Vector3()).applyMatrix4(node.matrixWorld),record={...meta,box,center,original:node.matrixWorld.clone()};records.push(record);const key=node.geometry.uuid+meta.group;if(!batchMap.has(key))batchMap.set(key,{geometry:node.geometry,material:node.material,records:[]});batchMap.get(key).records.push(record);});
 for(const b of batchMap.values()){const mesh=new THREE.InstancedMesh(b.geometry,b.material,b.records.length);mesh.userData.records=b.records;root.add(mesh);batches.push(mesh);b.records.forEach((r,i)=>{r.node=mesh;r.instance=i;});}
 sample.scene.updateMatrixWorld(true);sample.scene.traverse(n=>{if(!n.isMesh)return;const node=new THREE.Mesh(n.geometry,n.material);node.name=n.name;node.applyMatrix4(n.matrixWorld);node.geometry.computeBoundingBox();node.userData.original=node.position.clone();node.userData.layer=node.name.includes('shell')?'shell':node.name.includes('baffle')?'baffles':'board';node.userData.record={name:node.name,group:'prototype',box:node.geometry.boundingBox.clone()};prototype.add(node);});
 $('layers').replaceChildren(...Object.entries(groups).map(([id,[title,color]])=>{const label=document.createElement('label');label.className='layer';const input=document.createElement('input');input.type='checkbox';input.checked=true;input.dataset.layer=id;input.onchange=()=>{enabled[id]=input.checked;update();};const dot=document.createElement('i');dot.style.background=color;label.append(input,dot,document.createTextNode(title));return label;}));
 const resize=()=>{const r=$('scene').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();redraw();};new ResizeObserver(resize).observe($('scene'));resize();ready=true;update();reset();$('loading').hidden=true;$('load-detail').textContent=`${records.length.toLocaleString()} CAD parts and component envelopes`;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{mode=b.dataset.view;$('view-copy').textContent=mode==='prototype'?'Sample A1: the real-scale Vancouver fixture with revised grid clearance. Separate its layers and inspect the bench cradle.':'Rotate the assembly. Select a part to inspect its dimensions.';update();reset();});$('spread').oninput=()=>{spread=Number($('spread').value)/100;update();};$('reset').onclick=reset;$('save-image').onclick=()=>{renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='globe-CAD-'+mode+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});};
 const ray=new THREE.Raycaster();let down;renderer.domElement.onpointerdown=e=>{down=[e.clientX,e.clientY];};renderer.domElement.onpointerup=e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),camera);const hits=ray.intersectObject(mode==='prototype'?prototype:root,true).filter(h=>{let n=h.object;while(n){if(!n.visible)return false;n=n.parent;}return true;});if(hits[0]){const hit=hits[0],record=hit.object.userData.records?.[hit.instanceId]||hit.object.userData.record;if(record)select(record);}};
 window.globeEngineering={ready:true,snapshot:()=>({view:mode,parts:records.length,visible:records.filter(r=>r.visible).length,layers:{...enabled},prototypeVisible:prototype.visible,spread,triangles:renderer.info.render.triangles})};
}
load().catch(e=>{console.error(e);$('loading').innerHTML='The 3D assembly could not load. <a href="engineering-report.html">Open the illustrated engineering report</a> or try a browser with WebGL.';});
