// Optional UI test: install Playwright, provide Chromium, and serve dist/.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');

(async()=>{
  const out=path.resolve('artifacts');await fs.mkdir(out,{recursive:true});
  const url=process.env.GLOBE_TEST_URL||'http://127.0.0.1:4173/globe.html';
  const browser=await chromium.launch({executablePath:process.env.GLOBE_CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});
  const errors=[],requests=[];let checks=0;
  const check=(condition,message)=>{assert.ok(condition,message);checks++;console.log(`PASS ${message}`);};
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});
    const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.on('dialog',dialog=>dialog.accept());
    await page.goto(url);await page.waitForFunction(()=>window.globeStudy);
    const snapshot=()=>page.evaluate(()=>window.globeStudy.snapshot());
    const coverage=(lat,lon)=>page.evaluate(([lat,lon])=>window.globeStudy.coverageAt(lat,lon),[lat,lon]);
    const download=async(selector,name)=>{const promise=page.waitForEvent('download');await page.locator(selector).click();const file=await promise;const location=path.join(out,name);await file.saveAs(location);return fs.readFile(location);};
    check((await snapshot()).visits.length===1 && (await snapshot()).radius===50,'Vancouver opens with a 50-mile footprint');
    check(await coverage(49.2827,-123.1207)===1,'Vancouver is highlighted');
    check(await coverage(45.5019,-73.5674)===0 && await coverage(53.5461,-113.4938)===0,'distant Canada stays dark');
    check(await coverage(44.3683,-100.351)===0,'South Dakota stays dark');
    check(await page.locator('#connect, #engrave, .stop-connection').count()===0,'route and engraving controls have been removed');
    check((await snapshot()).exaggeration===25,'real terrain defaults to 25× vertical exaggeration');
    check(Math.abs(await page.evaluate(()=>window.globeStudy.elevationAt(28,86))-4045.45)<1,'browser uses the geographic elevation dataset');
    const terrainAtDefault=await page.evaluate(()=>window.globeStudy.terrainHeightAt(28,86));
    check(terrainAtDefault>2.4 && terrainAtDefault<2.45,'terrain relief has the correct millimetre scale');
    await page.locator('#relief').evaluate(el=>{el.value='0';el.dispatchEvent(new Event('input'));});
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('travel-globe-areas-v2')).exaggeration===0);
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).exaggeration===0 && await page.evaluate(()=>window.globeStudy.terrainHeightAt(28,86))===0,'flat terrain setting persists after reload');
    await page.locator('#relief').evaluate(el=>{el.value='25';el.dispatchEvent(new Event('input'));});
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('travel-globe-areas-v2')).exaggeration===25);
    await page.screenshot({path:path.join(out,'globe-desktop.png')});
    check(Math.abs(await page.evaluate(()=>window.globeStudy.dimensions().footprintDiameterMM)-3.85221505266)<1e-8,'physical scale remains correct');
    await page.locator('#land-only').uncheck();
    check(await coverage(49.2,-123.55)>0,'optional full footprint includes nearby water');
    await page.locator('#land-only').check();
    check(await coverage(49.2,-123.55)===0,'land mask clips offshore areas');
    await page.locator('#view-cap').click();check((await snapshot()).mode==='cap','curved print preview opens');
    await page.locator('.masthead').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'curved-section.png')});
    await page.locator('#led').check();check(await page.locator('#led').isChecked(),'coarse LED comparison renders');await page.locator('#led').uncheck();
    const shell=await download('#export-stl','example-light-only-shell-mm.stl'),count=shell.readUInt32LE(80);
    check(count===84096 && shell.length===84+count*50,'STL export contains the complete print shell');
    const carrier=await download('#export-carrier','example-led-carrier-mm.stl');
    check(carrier.readUInt32LE(80)===84096,'carrier STL downloads');
    const json=await download('#export-json','example-travels.json');
    check(JSON.parse(json).version===2 && JSON.parse(json).visits.length===1 && JSON.parse(json).radiusMiles===50,'JSON preserves places and footprint radius');
    await page.locator('#place-name').fill('New York test');await page.locator('#latitude').fill('40.7128');await page.locator('#longitude').fill('-74.006');await page.locator('#add-form button[type=submit]').click();
    check((await snapshot()).visits.length===2 && await coverage(44.3683,-100.351)===0,'adding a distant visit does not light the intervening ground');
    const unchanged=await download('#export-stl','shell-after-add-mm.stl');check(shell.equals(unchanged),'adding a visit leaves the printed shell byte-for-byte unchanged');
    await page.locator('#radius').evaluate(el=>{el.value='100';el.dispatchEvent(new Event('input'));});
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('travel-globe-areas-v2')).radius===100);
    check(shell.equals(await download('#export-stl','shell-after-radius-mm.stl')),'changing footprint radius leaves the printed shell unchanged');
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).visits.length===2 && (await snapshot()).radius===100,'visits and radius survive reload');
    await page.getByRole('button',{name:'Remove New York test',exact:true}).click();check((await snapshot()).visits.length===1,'place removal updates history');
    await page.locator('#file-input').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:2,visits:[{name:'Invalid',lat:999,lon:0}]}))});
    await page.waitForFunction(()=>document.getElementById('toast').textContent.startsWith('Import failed:'));
    check((await snapshot()).visits.length===1,'invalid imports preserve current history');
    await page.locator('#file-input').setInputFiles(path.join(out,'example-travels.json'));await page.waitForFunction(()=>window.globeStudy.snapshot().radius===50);
    check((await snapshot()).visits.length===1,'JSON import restores saved places and radius');
    await page.locator('#add-mode').click();const rect=await page.locator('#scene').boundingBox();await page.mouse.click(rect.x+rect.width/2,rect.y+rect.height/2);
    check((await page.locator('#latitude').inputValue())!=='' && (await page.locator('#longitude').inputValue())!=='','globe picking fills destination coordinates');
    await page.locator('#demo').selectOption('west');await page.locator('#load-demo').click();
    check(await coverage(42.7,-123)===0 && await coverage(44.3683,-100.351)===0,'scattered visits retain unvisited gaps and leave South Dakota dark');
    await page.locator('.masthead').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'scattered-visits.png')});
    await page.locator('#demo').selectOption('bay');await page.locator('#load-demo').click();
    check(await coverage(37.55,-122.15)>0.95,'nearby Bay Area visits merge into a continuous area');
    const legacy={version:1,stops:[{name:'Vancouver',lat:49.2827,lon:-123.1207,connect:false},{name:'New York',lat:40.7128,lon:-74.006,connect:true}]};
    await page.locator('#file-input').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
    await page.waitForFunction(()=>window.globeStudy.snapshot().visits.length===2);
    check(!(await snapshot()).visits.some(p=>'connect' in p) && await coverage(44.3683,-100.351)===0,'old route JSON imports only visited places');
    const dateline={version:2,radiusMiles:50,visits:[{name:'Date line test',lat:5,lon:179.8}]};
    await page.locator('#file-input').setInputFiles({name:'date.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(dateline))});
    await page.waitForFunction(()=>window.globeStudy.snapshot().visits.length===1);await page.locator('#land-only').uncheck();
    check(await coverage(5,-179.9)>0.99,'footprints cross the date line without a seam');
    await page.locator('#view-cap').click();await page.locator('#center-cap').click();check(Math.abs((await snapshot()).capLon)>170,'print section can center across the date line');
    await page.locator('#clear').click();await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).visits.length===0,'cleared history stays empty after reload');
    const oldState={stops:legacy.stops,demo:false,radius:75,height:0.7,brightness:65,engrave:true,capLat:40,capLon:-112};
    await page.evaluate(saved=>{localStorage.removeItem('travel-globe-areas-v2');localStorage.setItem('travel-globe-study-v1',JSON.stringify(saved));},oldState);
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).visits.length===2 && (await snapshot()).radius===75,'existing personal browser history migrates to area coverage');
    check((await snapshot()).exaggeration===25,'old texture amplitude migrates to a meaningful terrain default');
    check(await page.evaluate(saved=>localStorage.getItem('travel-globe-study-v1')===JSON.stringify(saved),oldState),'original browser history remains preserved after migration');
    const former=await snapshot();delete former.terrainRevision;former.exaggeration=4;
    await page.evaluate(saved=>localStorage.setItem('travel-globe-areas-v2',JSON.stringify(saved)),former);
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).exaggeration===25 && (await snapshot()).radius===75 && JSON.stringify((await snapshot()).visits)===JSON.stringify(former.visits),'returning visitors get stronger terrain without changing their history');
    await page.locator('#relief').evaluate(el=>{el.value='4';el.dispatchEvent(new Event('input'));});
    await page.waitForFunction(()=>JSON.parse(localStorage.getItem('travel-globe-areas-v2')).exaggeration===4);
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).exaggeration===4,'terrain migration runs once and respects later custom settings');
    delete former.terrainRevision;former.exaggeration=8;
    await page.evaluate(saved=>localStorage.setItem('travel-globe-areas-v2',JSON.stringify(saved)),former);
    await page.reload();await page.waitForFunction(()=>window.globeStudy);
    check((await snapshot()).exaggeration===8,'earlier custom terrain heights are preserved');
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
    const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(url);await phone.waitForFunction(()=>window.globeStudy);
    check(await phone.evaluate(()=>document.body.scrollWidth===innerWidth),'phone layout has no horizontal overflow');await phone.screenshot({path:path.join(out,'globe-mobile.png')});
    await phone.locator('#view-cap').click();check(await phone.locator('#print-controls').isVisible(),'print controls work on a phone');
    check(errors.length===0,`no browser runtime errors (${errors.join('; ')})`);
    check(requests.every(r=>r.startsWith(new URL(url).origin)||r.startsWith('data:')),'no external services are requested');
    console.log(`Completed ${checks} browser checks.`);
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
