"""Reproduce the bundled global elevation grid from pinned Basemap source data.

Run with Python + NumPy. Cached downloads are verified before they are used.
"""
from pathlib import Path
import base64
import hashlib
import json
import tempfile
import urllib.request
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
REVISION = "912b90bdf9245a84db5e523fef57b491b4b958e1"
BASE = f"https://raw.githubusercontent.com/matplotlib/basemap/{REVISION}/doc/examples/"
EXPECTED = {
    "etopo20data.gz": "bd6549bb0a675d2978d1dee1609fc4cec7e4d74b98d4fe49c0e8a2e8c8f3b8ce",
    "etopo20lons.gz": "95109988351bed186a886c6dd2a607455939013dfc49f7b7c61997d3389802b7",
    "etopo20lats.gz": "3201109f72a8371d1fee6396292618c9b05cae0a55abf8b2117bb2ef1f7e97ce",
}
arrays = {}
for name, digest in EXPECTED.items():
    cached = Path(tempfile.gettempdir()) / ("globe-" + name)
    if not cached.exists():
        with urllib.request.urlopen(BASE + name, timeout=60) as response:
            cached.write_bytes(response.read())
    assert hashlib.sha256(cached.read_bytes()).hexdigest() == digest, f"Checksum mismatch: {name}"
    arrays[name] = np.loadtxt(cached)

height, longitude, latitude = (arrays[n] for n in EXPECTED)
assert height.shape == (540, 1081) and longitude.shape == (1081,) and latitude.shape == (540,)
assert np.isfinite(height).all() and np.array_equal(height[:, 0], height[:, -1])
order = np.argsort((longitude[:-1] + 180) % 360 - 180)
assert np.allclose(((longitude[:-1] + 180) % 360 - 180)[order], -180 + (np.arange(1080) + 0.5) / 3, atol=0.0001)
assert np.allclose(latitude, -90 + (np.arange(540) + 0.5) / 3, atol=0.0001)
# Remove the duplicate cyclic column, reorder west-to-east and north-to-south,
# and quantize metres to int16 (at most 0.5 m quantization error).
metres = np.rint(height[::-1, :-1][:, order]).astype("<i2")
binary = metres.tobytes()
metadata = {
    "dataset": "ETOPO 20-arc-minute sample distributed with Matplotlib Basemap",
    "sourceRevision": REVISION,
    "width": 1080,
    "height": 540,
    "degreesPerCell": 1 / 3,
    "registration": "cell centers, west=-180, north=90, rows north-to-south",
    "units": "metres, signed little-endian int16",
    "minimumMeters": int(metres.min()),
    "maximumMeters": int(metres.max()),
    "sha256": hashlib.sha256(binary).hexdigest(),
    "samplesBase64": base64.b64encode(binary).decode("ascii"),
}
destination = ROOT / "preview/data/elevation-grid.js"
destination.write_text("// Generated by tools/prepare-elevation.py; see docs/elevation.md.\nexport default " + json.dumps(metadata, separators=(",", ":")) + ";\n")
print(f"Prepared {metres.shape[1]} x {metres.shape[0]} real elevation samples: {metres.min()} to {metres.max()} m")
print(f"Grid SHA-256: {metadata['sha256']}")
